# Generated by Django 5.0.6 on 2024-06-02 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_record_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('project_discription', models.CharField(max_length=300)),
                ('project_cost', models.CharField(max_length=100)),
                ('project_start_date', models.DateField()),
                ('project_deadLine', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='project',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='project_cost',
        ),
        migrations.RemoveField(
            model_name='record',
            name='project_deadLine',
        ),
        migrations.RemoveField(
            model_name='record',
            name='project_discription',
        ),
        migrations.RemoveField(
            model_name='record',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='record',
            name='employee_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='employee_projects',
            field=models.ManyToManyField(to='webapp.projects'),
        ),
    ]
