# Generated by Django 5.0.6 on 2024-06-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_projects_rename_project_record_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
