# Generated by Django 5.0.6 on 2024-06-03 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='employee_projects',
        ),
        migrations.AddField(
            model_name='project',
            name='employee_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='employee_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
